name: Quality

on:
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.json'
      - '**/*.mjs'
      - '**/*.cjs'
      - '.github/workflows/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig*.json'
      - 'eslint*'
  push:
    branches: [main]
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.json'
      - '**/*.mjs'
      - '**/*.cjs'
      - '.github/workflows/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig*.json'
      - 'eslint*'

concurrency:
  group: quality-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js (from .nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install deps (clean)
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type check (CI mode)
        run: npm run type-check:ci
