name: Type Check

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: type-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'
          cache: 'npm'

      - name: Install deps (clean)
        run: npm ci

      - name: Type check (CI mode)
        run: npm run type-check:ci
